package se.fk.github.Beslut;

public enum BeslutandeOrganisation {
    HUSDJURSMYNDIGHETEN,
    FORSAKRINGSKASSAN,
    FORVALTNINGSRATTEN,
    KAMMARRATTEN,
    HOGSTA_FORVALTNINGSDOMSTOLEN,
    MIGRATIONSVERKET,
    ARBETSFORMEDLINGEN,
    TINGSRATTEN,
    SKATTEVERKET
}
