package se.fk.github.Uppgift;

public enum FSSAInformation {
    ARENDE_NYSKAPAD,
    TILLDELAD_TILL_HANDLAGGARE,
    HANDLAGGNING_PAGAR,
    VANTAR_PA_INTERN_INFORMATION,
    VANTAR_PA_EXTERN_INFORMATION,
    VANTAR_PA_INFORMATION_FRAN_DIG,
    UTFALL_SAMMANSTALLS,
    ARENDE_AVSLUTAT

}
